"""Recipe category tree (approved in session 4). Source: 02 - Producto document.

Each entry: (slug, name_es, name_en, examples_es, children)
"""

SALADO = [
    (
        "aperitivos-tapas",
        "Aperitivos y tapas",
        "Appetisers & tapas",
        None,
        [
            ("tapas-frias", "Tapas frías", "Cold tapas", None),
            ("tapas-calientes", "Tapas calientes", "Hot tapas", None),
            ("frituras", "Frituras", "Fried bites", "croquetas, pescaíto, buñuelos salados"),
            ("untables-dips", "Untables y dips", "Spreads & dips", "hummus, patés, guacamole"),
            (
                "encurtidos-conservas",
                "Encurtidos y conservas",
                "Pickles & preserves",
                "aliños, aceitunas, boquerones en vinagre",
            ),
            ("bocadillos-montaditos", "Bocadillos y montaditos", "Sandwiches & bites", None),
        ],
    ),
    (
        "ensaladas",
        "Ensaladas",
        "Salads",
        None,
        [
            ("ensaladas-verdes", "Ensaladas verdes", "Leafy salads", None),
            (
                "ensaladas-legumbres-arroz-pasta",
                "Ensaladas de legumbres, arroz y pasta",
                "Grain & pulse salads",
                None,
            ),
            (
                "ensaladas-verduras-frutas",
                "Ensaladas de verduras y frutas",
                "Vegetable & fruit salads",
                "pipirrana, remojón",
            ),
            (
                "ensaladas-pescado-carne",
                "Ensaladas con pescado o carne",
                "Salads with fish or meat",
                None,
            ),
            ("ensaladas-templadas", "Ensaladas templadas", "Warm salads", None),
        ],
    ),
    (
        "sopas-cremas-caldos",
        "Sopas, cremas y caldos",
        "Soups & broths",
        None,
        [
            ("sopas-frias", "Sopas frías", "Cold soups", "gazpacho, salmorejo, ajoblanco"),
            ("sopas-calientes", "Sopas calientes", "Hot soups", "sopa de picadillo, sopa de ajo"),
            ("cremas-pures", "Cremas y purés", "Creamy soups", None),
            ("caldos-fondos", "Caldos y fondos", "Stocks & broths", "caldo de puchero, fumet"),
        ],
    ),
    (
        "verduras-hortalizas",
        "Verduras y hortalizas",
        "Vegetables",
        None,
        [
            (
                "verduras-cocinadas",
                "Verduras cocinadas",
                "Cooked vegetables",
                "salteados, hervidos, al vapor",
            ),
            ("verduras-asadas", "Verduras asadas y al horno", "Roasted vegetables", None),
            ("verduras-rellenas", "Verduras rellenas", "Stuffed vegetables", None),
            ("setas", "Setas", "Mushrooms", None),
            ("patatas", "Patatas", "Potatoes", None),
            ("guarniciones", "Guarniciones", "Side dishes", None),
        ],
    ),
    (
        "legumbres",
        "Legumbres",
        "Pulses",
        None,
        [
            (
                "cocidos-potajes",
                "Cocidos y potajes",
                "Cocidos & potajes",
                "puchero, potaje de garbanzos",
            ),
            ("guisos-legumbres", "Guisos de legumbres", "Pulse stews", "lentejas, fabada, alubias"),
            ("legumbres-frias", "Legumbres frías y cremas de legumbre", "Cold pulse dishes", None),
        ],
    ),
    (
        "arroces-cereales",
        "Arroces y cereales",
        "Rice & grains",
        None,
        [
            ("arroces-secos", "Arroces secos", "Dry rice, paella-style", None),
            ("arroces-melosos-caldosos", "Arroces melosos y caldosos", "Soupy & creamy rice", None),
            ("risottos", "Risottos", "Risottos", None),
            (
                "arroces-mundo",
                "Arroces del mundo",
                "World rice dishes",
                "pilaf, biryani, arroz frito, sushi",
            ),
            ("otros-cereales", "Otros cereales", "Other grains", "cuscús, quinoa, bulgur, polenta"),
        ],
    ),
    (
        "pasta-fideos",
        "Pasta y fideos",
        "Pasta & noodles",
        None,
        [
            ("pasta-salsa", "Pasta con salsa", "Pasta with sauce", None),
            (
                "pasta-horno",
                "Pasta al horno",
                "Baked pasta",
                "lasaña, canelones, macarrones gratinados",
            ),
            ("pasta-rellena", "Pasta rellena", "Filled pasta", None),
            ("fideua-fideos", "Fideuá y fideos", "Fideuá & Spanish noodles", None),
            ("fideos-asiaticos", "Fideos asiáticos", "Asian noodles", None),
            ("noquis-pasta-fresca", "Ñoquis y pasta fresca", "Gnocchi & fresh pasta", None),
        ],
    ),
    (
        "huevos",
        "Huevos",
        "Eggs",
        None,
        [
            ("tortillas", "Tortillas", "Spanish omelettes & omelettes", None),
            ("revueltos", "Revueltos", "Scrambled eggs", None),
            (
                "huevos-fritos-escalfados",
                "Huevos fritos, escalfados y al plato",
                "Fried, poached & baked eggs",
                None,
            ),
            ("quiches", "Quiches y tartas saladas de huevo", "Quiches", None),
        ],
    ),
    (
        "pescados",
        "Pescados",
        "Fish",
        None,
        [
            (
                "pescado-blanco",
                "Pescado blanco",
                "White fish",
                "merluza, bacalao fresco, lubina, dorada",
            ),
            (
                "pescado-azul",
                "Pescado azul",
                "Oily fish",
                "sardinas, boquerones, atún, salmón, caballa",
            ),
            ("bacalao-salado", "Bacalao salado", "Salt cod", None),
            (
                "pescado-plancha-parrilla",
                "Pescado a la plancha y a la parrilla",
                "Grilled fish",
                None,
            ),
            ("pescado-horno-sal", "Pescado al horno y a la sal", "Baked fish", None),
            ("frituras-pescado", "Frituras de pescado", "Fried fish", "pescaíto frito, adobo"),
            ("guisos-pescado", "Guisos de pescado", "Fish stews", "suquet, marmitako, caldereta"),
            (
                "pescado-crudo-marinado",
                "Pescado crudo y marinado",
                "Raw & cured fish",
                "ceviche, tartar, escabeche",
            ),
            ("conservas-pescado", "Conservas de pescado", "Tinned fish dishes", None),
        ],
    ),
    (
        "mariscos",
        "Mariscos",
        "Seafood",
        None,
        [
            ("gambas-langostinos", "Gambas y langostinos", "Prawns", None),
            (
                "calamares-sepia-pulpo",
                "Calamares, sepia y pulpo",
                "Squid, cuttlefish & octopus",
                None,
            ),
            (
                "mejillones-almejas",
                "Mejillones, almejas y otros moluscos",
                "Mussels, clams & shellfish",
                None,
            ),
            (
                "cangrejo-bogavante",
                "Cangrejo, bogavante y otros crustáceos",
                "Crab, lobster & crustaceans",
                None,
            ),
            ("guisos-arroces-marisco", "Guisos y arroces de marisco", "Seafood stews", None),
        ],
    ),
    (
        "carnes",
        "Carnes",
        "Meat",
        None,
        [
            ("pollo-aves", "Pollo y aves", "Chicken & poultry", "pollo, pavo, pato, codorniz"),
            ("cerdo", "Cerdo", "Pork", "ibéricos, presa, secreto, carrillada"),
            ("ternera-vacuno", "Ternera y vacuno", "Beef & veal", None),
            ("cordero-cabrito", "Cordero y cabrito", "Lamb & kid", None),
            ("conejo", "Conejo", "Rabbit", None),
            ("caza", "Caza", "Game", "venado, jabalí, perdiz"),
            (
                "carne-picada",
                "Carne picada",
                "Minced meat",
                "albóndigas, hamburguesas, pasteles de carne",
            ),
            ("casqueria", "Casquería", "Offal", "callos, menudo, hígado"),
            ("embutidos-charcuteria", "Embutidos y charcutería casera", "Charcuterie", None),
        ],
    ),
    (
        "guisos-cuchara",
        "Guisos y platos de cuchara",
        "Stews & one-pot dishes",
        None,
        [
            (
                "guisos-carne",
                "Guisos de carne",
                "Meat stews",
                "ropa vieja, carne con tomate, rabo de toro",
            ),
            (
                "guisos-verduras",
                "Guisos de verduras",
                "Vegetable stews",
                "pisto, alboronía, menestra",
            ),
            ("guisos-mundo", "Guisos del mundo", "World stews", "curry, chili, tajín, goulash"),
        ],
    ),
    (
        "masas-saladas-panes",
        "Masas saladas y panes",
        "Savoury bakes & bread",
        None,
        [
            ("pan", "Pan", "Bread", "pan de pueblo, molletes, regañás, pan de masa madre"),
            ("pizzas-cocas", "Pizzas y cocas", "Pizzas & flatbreads", None),
            ("empanadas-empanadillas", "Empanadas y empanadillas", "Pies & pasties", None),
            (
                "hojaldres-tartas-saladas",
                "Hojaldres y tartas saladas",
                "Savoury pastries & tarts",
                None,
            ),
            (
                "masas-mundo",
                "Masas del mundo",
                "World doughs",
                "tortillas de maíz, naan, pita, dumplings",
            ),
        ],
    ),
    (
        "salsas-alinos-basicos",
        "Salsas, aliños y básicos",
        "Sauces, dressings & basics",
        None,
        [
            ("salsas-frias", "Salsas frías", "Cold sauces", "mayonesa, alioli, vinagretas"),
            (
                "salsas-calientes",
                "Salsas calientes",
                "Hot sauces",
                "tomate, bechamel, salsa española",
            ),
            ("adobos-marinadas", "Adobos y marinadas", "Marinades & rubs", None),
            ("mezclas-especias-caseras", "Mezclas de especias caseras", "Spice blends", None),
            (
                "basicos-despensa",
                "Básicos de despensa",
                "Pantry basics",
                "caldo concentrado, sofrito, tomate frito",
            ),
        ],
    ),
]

DULCE = [
    (
        "tartas-bizcochos",
        "Tartas y bizcochos",
        "Cakes",
        None,
        [
            ("bizcochos", "Bizcochos", "Sponge cakes", "bizcocho de yogur, de limón, de zanahoria"),
            ("tartas-queso", "Tartas de queso", "Cheesecakes", None),
            ("tartas-frutas", "Tartas de frutas", "Fruit tarts", None),
            (
                "tartas-chocolate-brownies",
                "Tartas de chocolate y brownies",
                "Chocolate cakes & brownies",
                None,
            ),
            ("tartas-frias", "Tartas frías y sin horno", "No-bake cakes", None),
            (
                "tartas-celebracion",
                "Tartas de celebración",
                "Celebration cakes",
                "tartas por capas, cumpleaños",
            ),
            ("magdalenas-muffins", "Magdalenas, muffins y cupcakes", "Muffins & cupcakes", None),
        ],
    ),
    (
        "galletas-pastas",
        "Galletas y pastas",
        "Biscuits & cookies",
        None,
        [
            ("galletas", "Galletas", "Cookies", None),
            ("pastas-te", "Pastas de té", "Shortbread & tea biscuits", None),
            ("galletas-decoradas", "Galletas decoradas", "Decorated cookies", None),
            (
                "barritas-crujientes",
                "Barritas y crujientes",
                "Bars & crisps",
                "barritas de avena, granola",
            ),
        ],
    ),
    (
        "bolleria-masas-dulces",
        "Bollería y masas dulces",
        "Pastries & sweet doughs",
        None,
        [
            (
                "bolleria-levadura",
                "Bollería de levadura",
                "Yeasted pastries",
                "roscón, brioche, bollos de leche, ensaimada",
            ),
            (
                "hojaldre-dulce",
                "Hojaldre dulce",
                "Sweet puff pastry",
                "palmeras, milhojas, napolitanas",
            ),
            ("masas-fritas", "Masas fritas", "Fried doughs", "churros, buñuelos, rosquillas"),
            (
                "crepes-gofres-tortitas",
                "Crepes, gofres y tortitas",
                "Crêpes, waffles & pancakes",
                None,
            ),
            ("panes-dulces", "Panes dulces", "Sweet breads", "pan de plátano, panettone"),
        ],
    ),
    (
        "postres-cuchara",
        "Postres de cuchara",
        "Spoon desserts",
        None,
        [
            ("flanes-natillas", "Flanes y natillas", "Flans & custards", None),
            (
                "cremas-mousses",
                "Cremas y mousses",
                "Creams & mousses",
                "crema catalana, mousse de chocolate",
            ),
            (
                "arroz-con-leche-postres-leche",
                "Arroz con leche y postres de leche",
                "Milk desserts",
                "arroz con leche, leche frita, cuajada",
            ),
            ("gelatinas-panna-cotta", "Gelatinas y panna cotta", "Jellies & panna cotta", None),
            ("puddings", "Puddings y pudines", "Puddings", None),
            (
                "tiramisu-postres-vaso",
                "Tiramisú y postres montados en vaso",
                "Layered desserts",
                None,
            ),
        ],
    ),
    (
        "postres-frutas",
        "Postres de frutas",
        "Fruit desserts",
        None,
        [
            (
                "frutas-asadas",
                "Frutas asadas y al horno",
                "Baked fruit",
                "manzanas asadas, crumbles",
            ),
            ("compotas-almibar", "Compotas y frutas en almíbar", "Compotes & syrup fruit", None),
            ("macedonias-frutas-frescas", "Macedonias y frutas frescas", "Fresh fruit", None),
            ("frutas-rellenas-crema", "Frutas rellenas o con crema", "Fruit with cream", None),
        ],
    ),
    (
        "helados-sorbetes",
        "Helados y sorbetes",
        "Ice creams & sorbets",
        None,
        [
            ("helados", "Helados", "Ice creams", None),
            ("sorbetes-granizados", "Sorbetes y granizados", "Sorbets & granitas", None),
            ("polos", "Polos", "Ice lollies", None),
        ],
    ),
    (
        "chocolate-bombones",
        "Chocolate y bombones",
        "Chocolate & confectionery",
        None,
        [
            ("bombones-trufas", "Bombones y trufas", "Chocolates & truffles", None),
            (
                "caramelos-toffees",
                "Caramelos, toffees y turrón blando",
                "Caramels & soft nougat",
                None,
            ),
            (
                "garrapinados-crocantes",
                "Frutos secos garrapiñados y crocantes",
                "Candied nuts & brittle",
                None,
            ),
        ],
    ),
    (
        "dulces-tradicionales",
        "Dulces tradicionales",
        "Traditional sweets",
        None,
        [
            (
                "dulces-fritos",
                "Dulces fritos",
                "Fried traditional sweets",
                "torrijas, pestiños, buñuelos de viento",
            ),
            (
                "dulces-almendra",
                "Dulces de almendra",
                "Almond sweets",
                "mazapán, turrón, polvorones, mantecados",
            ),
            (
                "dulces-conventuales",
                "Dulces conventuales",
                "Convent sweets",
                "yemas, tocino de cielo, huesos de santo",
            ),
            (
                "dulces-miel-frutos-secos",
                "Dulces de miel y frutos secos",
                "Honey & nut sweets",
                "alfajores, piñonate",
            ),
            ("reposteria-regional", "Repostería regional", "Regional pastries", None),
        ],
    ),
    (
        "mermeladas-conservas-dulces",
        "Mermeladas y conservas dulces",
        "Jams & sweet preserves",
        None,
        [
            ("mermeladas-confituras", "Mermeladas y confituras", "Jams", None),
            ("frutas-confitadas", "Frutas confitadas", "Candied fruit", None),
            (
                "membrillo-pastas-fruta",
                "Dulce de membrillo y pastas de fruta",
                "Fruit pastes",
                None,
            ),
        ],
    ),
    (
        "cremas-rellenos-coberturas",
        "Cremas, rellenos y coberturas",
        "Fillings, creams & frostings",
        None,
        [
            ("cremas-pasteleras-curds", "Cremas pasteleras y curds", "Pastry creams & curds", None),
            (
                "ganaches-coberturas",
                "Ganaches y coberturas de chocolate",
                "Ganaches & chocolate glazes",
                None,
            ),
            ("merengues", "Merengues", "Meringues", None),
            ("glaseados-buttercream", "Glaseados y buttercream", "Icings & buttercream", None),
            ("almibares-caramelo", "Almíbares y caramelo", "Syrups & caramel", None),
        ],
    ),
]

BEBIDAS = [
    ("batidos-zumos", "Batidos y zumos", "Smoothies & juices", None, []),
    (
        "bebidas-calientes",
        "Bebidas calientes",
        "Hot drinks",
        "chocolate a la taza, cafés, infusiones",
        [],
    ),
    (
        "bebidas-frias-sin-alcohol",
        "Bebidas frías sin alcohol",
        "Cold soft drinks",
        "limonada, horchata",
        [],
    ),
    ("cocteles-combinados", "Cócteles y combinados", "Cocktails", None, []),
    ("sangrias-rebujitos-ponches", "Sangrías, rebujitos y ponches", "Sangrias & punches", None, []),
    ("licores-caseros", "Licores caseros", "Homemade liqueurs", "licor de café, resolí", []),
]

TREE = [
    ("salado", "Salado", "Savoury", SALADO),
    ("dulce", "Dulce", "Sweet", DULCE),
    ("bebidas", "Bebidas", "Drinks", BEBIDAS),
]
