"""Fifty everyday recipes, Spanish and international, to try the notebook and the weekly menu
with (session 9). Each one is imported from its page on directoalpaladar.com with the app's
importer, so the notebook keeps the link and the site.

Each line: (page path, category slug, course tag code or None, seasons). The category, the
moment and the seasons are decided by hand here, as the person would do when importing; the
importer only reads the recipe. Course tags: "main", "light-dinner", "breakfast",
"dessert", "appetiser", "starter", "side".
"""

SITE = "https://www.directoalpaladar.com/"

DEMO_RECIPES: list[tuple[str, str, str | None, list[str]]] = [
    # --- Guisos, legumbres y cuchara (comidas) ---
    (
        "recetas-de-legumbres-y-verduras/lentejas-chorizo-receta-guiso-que-todos-disfrutaran-legumbres",
        "guisos-legumbres",
        "main",
        ["autumn", "winter"],
    ),
    (
        "recetas-de-legumbres/receta-garbanzos-chorizo-plato-cuchara-sencillo-sabroso",
        "guisos-legumbres",
        "main",
        ["autumn", "winter"],
    ),
    (
        "recetas-de-legumbres-y-verduras/receta-de-fabada-asturiana-al-estilo-tradicional",
        "guisos-legumbres",
        "main",
        ["winter"],
    ),
    (
        "recetas-de-legumbres-y-verduras/receta-de-cocido-madrileno",
        "cocidos-potajes",
        "main",
        ["winter"],
    ),
    (
        "recetas-de-legumbres/puchero-canario-delicioso-plato-cuchara-que-debes-probar-este-invierno",
        "cocidos-potajes",
        "main",
        ["winter"],
    ),
    (
        "recetas-de-legumbres-y-verduras/patatas-a-la-riojana-de-mi-suegra-receta",
        "guisos-verduras",
        "main",
        ["autumn", "winter"],
    ),
    (
        "recetas-de-legumbres-y-verduras/receta-menestra-carne-plato-completo-que-saciarse-hacer-excesos",
        "guisos-verduras",
        "main",
        ["spring"],
    ),
    (
        "recetas-de-carnes-y-aves/carrilleras-ternera-guisadas-vino-tinto-receta-tradicional",
        "guisos-carne",
        "main",
        ["autumn", "winter"],
    ),
    (
        "recetas-de-carnes-y-aves/guiso-pollo-15-minutos-que-sabe-al-abuela-que-descubri-este-truco-no-cocino-otra-manera",
        "guisos-carne",
        "main",
        [],
    ),
    (
        "recetas-de-pescados-y-mariscos/chipirones-patatas-guiso-tradicional-sencillo-economico-perfecto-para-mojar-pan",
        "guisos-pescado",
        "main",
        [],
    ),
    # --- Arroces y pasta ---
    (
        "recetas-de-arroces/paella-valenciana-receta-tradicional",
        "arroces-secos",
        "main",
        [],
    ),
    (
        "recetas-de-arroces/paella-de-pollo-y-conejo-receta-tradicional",
        "arroces-secos",
        "main",
        [],
    ),
    (
        "recetas-de-arroces/arroz-carne-receta-tradicional-que-nunca-falla",
        "arroces-secos",
        "main",
        [],
    ),
    (
        "recetas-de-arroces/risotto-negro-receta-cremosa-facil-espectacular",
        "risottos",
        "main",
        [],
    ),
    (
        "recetas-de-arroces/arroz-frito-ajo-khao-pad-kra-tiam-receta-tailandesa-sencilla-hacer",
        "arroces-mundo",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-pasta/como-hacer-espaguetis-a-la-carbonara-mejor-que-en-ningun-restaurante",
        "pasta-salsa",
        "main",
        [],
    ),
    (
        "recetas-de-pasta/receta-macarrones-carne-receta-facil-para-toda-familia",
        "pasta-salsa",
        "main",
        [],
    ),
    (
        "recetas-de-pasta/receta-espaguetis-a-amatriciana-spaghetti-all-amatriciana-tradicional-italiana",
        "pasta-salsa",
        "main",
        [],
    ),
    (
        "recetas-de-pasta/lasana-de-carne-a-la-bolonesa-receta",
        "pasta-horno",
        "main",
        [],
    ),
    (
        "recetas-de-pasta/pasta-primavera-receta-facil-perfecta-para-aprovechar-verduras-temporada",
        "pasta-salsa",
        "light-dinner",
        ["spring", "summer"],
    ),
    (
        "recetas-de-pasta/pad-woon-sen-receta-tailandesa-fideos-cristal-salteados-pollo-verduras-que-se-prepara-periquete",
        "fideos-asiaticos",
        "light-dinner",
        [],
    ),
    # --- Carnes ---
    (
        "recetas-de-carnes-y-aves/receta-tradicional-de-pollo-al-ajillo",
        "pollo-aves",
        "main",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/pollo-al-horno",
        "pollo-aves",
        "main",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/receta-de-pollo-al-curry-en-10-minutos",
        "pollo-aves",
        "main",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/albondigas-pepitoria-tiernas-jugosas-llenas-sabor",
        "carne-picada",
        "main",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/como-hacer-hamburguesas-caseras",
        "carne-picada",
        "main",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/tacos-mexicanos-de-ternera-receta",
        "ternera-vacuno",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/solomillo-cerdo-manzana-receta-tradicional-facil-jugosa-para-resolver-comida-especial",
        "cerdo",
        "main",
        ["autumn", "winter"],
    ),
    (
        "recetas-de-carnes-y-aves/pluma-iberica-a-plancha-mejor-forma-cocinar-casa-uno-cortes-nobles-cerdo",
        "cerdo",
        "main",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/milanesas-ternera-receta-clasica-tradicional-secreto-no-se-despegue-rebozado",
        "ternera-vacuno",
        "main",
        [],
    ),
    (
        "recetas-de-carnes-y-aves/schnitzel-receta-tradicional-autentico-escalope-vienes",
        "cerdo",
        "main",
        [],
    ),
    # --- Pescados y mariscos ---
    (
        "recetas-de-pescados-y-mariscos/como-hacer-merluza-en-salsa-verde-receta",
        "pescado-blanco",
        "main",
        [],
    ),
    (
        "recetas-tradicionales/bacalao-al-pil-pil-descubre-esta-joya-gastronomia-vasca",
        "bacalao-salado",
        "main",
        [],
    ),
    (
        "recetas-de-pescados-y-mariscos/salmon-al-horno-la-receta-mas-facil-del-mundo",
        "pescado-horno-sal",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-pescados-y-mariscos/dorada-al-horno-con-patatas-receta",
        "pescado-horno-sal",
        "main",
        [],
    ),
    (
        "recetas-de-pescados-y-mariscos/gambas-papillote-receta-muy-facil-que-tienes-lista-5-minutos",
        "gambas-langostinos",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-pescados-y-mariscos/esta-cena-saludable-sabe-a-cadiz-se-resuelve-media-hora-atun-cebolla-poco",
        "pescado-azul",
        "light-dinner",
        [],
    ),
    # --- Verduras, huevos, ensaladas, sopas (cenas) ---
    (
        "recetas-de-legumbres-y-verduras/pisto-manchego-receta",
        "verduras-cocinadas",
        "light-dinner",
        ["summer"],
    ),
    (
        "recetas-de-legumbres-y-verduras/judias-verdes-jamon-receta-facil-e-irresistible-para-reivindicar-este-clasico-1",
        "verduras-cocinadas",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-huevos-y-tortillas/empezando-en-la-cocina-receta-de-tortilla-de-patatas-con-cebolla",
        "tortillas",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-huevos-y-tortillas/huevos-rotos-jamon-clasico-que-nunca-falla",
        "huevos-fritos-escalfados",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-legumbres-y-verduras/tortilla-alcachofas-receta-ligera-ideal-para-cena",
        "tortillas",
        "light-dinner",
        ["winter", "spring"],
    ),
    (
        "recetas-de-huevos-y-tortillas/tortilla-acelgas-receta-facil-para-cena-rapida-saludable",
        "tortillas",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-sopas-y-cremas/receta-de-gazpacho-andaluz-tradicional",
        "sopas-frias",
        "light-dinner",
        ["summer"],
    ),
    (
        "recetas-de-sopas-y-cremas/receta-de-salmorejo-cordobes-tradicional",
        "sopas-frias",
        "light-dinner",
        ["summer"],
    ),
    (
        "recetas-de-sopas-y-cremas/crema-calabaza-receta-casera-facil-siete-trucos-quede-perfecta",
        "cremas-pures",
        "light-dinner",
        ["autumn", "winter"],
    ),
    (
        "recetas-de-sopas-y-cremas/tom-kha-gai-sopa-tailandesa-pollo-coco-muy-aromatica",
        "sopas-calientes",
        "light-dinner",
        [],
    ),
    (
        "recetas-de-ensaladas/como-hacer-ensaladilla-rusa-matricula-honor-seguimos-recomendaciones-chef-juan-pozuelo",
        "ensaladas-pescado-carne",
        "light-dinner",
        ["summer"],
    ),
    (
        "recetas-de-ensaladas/empedrado-garbanzos-receta-super-fresquita-para-verano-facil-rica-proteinas",
        "ensaladas-legumbres-arroz-pasta",
        "light-dinner",
        ["summer"],
    ),
    # --- Aperitivos y postres (no salen como comida ni cena) ---
    (
        "recetas-de-aperitivos/croquetas-jamon-receta-toda-vida-que-no-sabe-modas-siempre-triunfa",
        "frituras",
        "appetiser",
        [],
    ),
    (
        "postres/flan-cafe-facil-delicioso-esta-mejor-receta-que-vas-a-encontrar-1",
        "flanes-natillas",
        "dessert",
        [],
    ),
]
