"""Everyday ingredients with their supermarket section (session 9), so that the shopping list
sorts itself. Spices and the fresh ingredients of the spice zone are in spices.py.

Each line: "name | English name | other names". The name is singular and in lowercase; the
seed adds the plurals ("patata" → "patatas", "limón" → "limones") and the English name as
other names, so "2 kg de patatas" and "potatoes" land in Frutas y verduras.
"""

INGREDIENTS: dict[str, list[str]] = {
    "produce": [
        "patata | potato | papa", "tomate | tomato", "tomate cherry | cherry tomato",
        "pimiento rojo | red pepper", "pimiento verde | green pepper",
        "pimiento italiano | italian pepper", "pimiento de padrón | padrón pepper",
        "zanahoria | carrot", "calabacín | courgette | zucchini", "berenjena | aubergine",
        "calabaza | pumpkin", "pepino | cucumber", "lechuga | lettuce",
        "espinaca | spinach", "acelga | chard", "col | cabbage | repollo",
        "coliflor | cauliflower", "brócoli | broccoli", "alcachofa | artichoke",
        "espárrago | asparagus | espárrago verde", "judía verde | green bean",
        "guisante | pea", "haba | broad bean", "champiñón | mushroom",
        "seta | wild mushroom", "boniato | sweet potato | batata", "remolacha | beetroot",
        "rábano | radish", "nabo | turnip", "canónigo | lamb's lettuce", "rúcula | rocket",
        "endibia | endive", "escarola | escarole", "maíz dulce | sweetcorn | mazorca",
        "aguacate | avocado", "manzana | apple", "pera | pear", "plátano | banana",
        "fresa | strawberry", "frambuesa | raspberry", "arándano | blueberry",
        "uva | grape", "melocotón | peach", "nectarina | nectarine", "albaricoque | apricot",
        "ciruela | plum", "cereza | cherry", "sandía | watermelon", "melón | melon",
        "piña | pineapple", "mango | mango", "kiwi | kiwi", "granada | pomegranate",
        "higo | fig", "mandarina | mandarin", "pomelo | grapefruit", "membrillo | quince",
        "caqui | persimmon", "coco | coconut",
    ],
    "meat": [
        "pollo | chicken", "pechuga de pollo | chicken breast",
        "muslo de pollo | chicken thigh | contramuslo de pollo", "alita de pollo | chicken wing",
        "pavo | turkey", "pechuga de pavo | turkey breast", "carne picada | minced meat",
        "ternera | beef | vaca", "filete de ternera | beef steak", "solomillo | tenderloin",
        "entrecot | ribeye", "morcillo | beef shin", "rabo de toro | oxtail",
        "cerdo | pork", "lomo de cerdo | pork loin", "costilla de cerdo | pork ribs | costilla",
        "secreto ibérico | ibérico secreto", "presa ibérica | ibérico presa",
        "carrillada | pork cheek | carrillera", "panceta | pork belly",
        "cordero | lamb", "paletilla de cordero | lamb shoulder",
        "chuleta de cordero | lamb chop", "conejo | rabbit", "codorniz | quail",
        "pato | duck", "hígado | liver", "jamón serrano | serrano ham",
        "jamón ibérico | ibérico ham", "jamón cocido | cooked ham | jamón york",
        "chorizo | chorizo", "morcilla | black pudding", "salchicha | sausage",
        "salchichón | salchichón", "lomo embuchado | cured pork loin", "bacon | bacon | beicon",
        "tocino | fatback", "sobrasada | sobrasada", "longaniza | longaniza",
        "hueso de jamón | ham bone", "hueso de caña | marrow bone",
    ],
    "fish": [
        "merluza | hake", "bacalao | cod", "bacalao en salazón | salt cod",
        "salmón | salmon", "salmón ahumado | smoked salmon", "atún | tuna",
        "bonito | bonito", "sardina | sardine", "boquerón | anchovy",
        "caballa | mackerel", "dorada | gilthead bream", "lubina | sea bass",
        "rape | monkfish", "rodaballo | turbot", "lenguado | sole", "gallo | megrim",
        "pez espada | swordfish", "emperador | swordfish steak", "trucha | trout",
        "pulpo | octopus", "calamar | squid", "chipirón | baby squid", "sepia | cuttlefish",
        "gamba | prawn", "langostino | king prawn", "cigala | langoustine",
        "mejillón | mussel", "almeja | clam", "berberecho | cockle", "navaja | razor clam",
        "vieira | scallop", "cangrejo | crab", "surimi | surimi | palito de cangrejo",
    ],
    "dairy": [
        "huevo | egg", "leche | milk", "leche desnatada | skimmed milk",
        "leche semidesnatada | semi-skimmed milk", "nata | cream | nata para cocinar",
        "nata para montar | whipping cream", "mantequilla | butter", "margarina | margarine",
        "yogur | yogurt | yogur natural", "yogur griego | greek yogurt",
        "queso | cheese", "queso fresco | fresh cheese | queso de burgos",
        "queso rallado | grated cheese", "queso manchego | manchego cheese",
        "queso curado | cured cheese", "queso de cabra | goat cheese", "queso azul | blue cheese",
        "mozzarella | mozzarella", "parmesano | parmesan", "requesón | ricotta | ricotta",
        "queso crema | cream cheese", "mascarpone | mascarpone", "feta | feta",
        "crème fraîche | crème fraîche", "kéfir | kefir", "cuajada | junket",
        "bebida de avena | oat milk", "bebida de soja | soy milk",
    ],
    "bakery": [
        "pan | bread", "pan de molde | sliced bread", "pan rallado | breadcrumbs",
        "barra de pan | baguette", "pan integral | wholemeal bread", "picatoste | crouton",
        "pan de hamburguesa | burger bun", "tortilla de trigo | wheat tortilla",
        "masa de hojaldre | puff pastry | hojaldre", "masa quebrada | shortcrust pastry",
        "masa de pizza | pizza dough", "oblea para empanadilla | dumpling wrapper",
        "bizcocho | sponge cake", "magdalena | muffin", "croissant | croissant | cruasán",
        "pan de pita | pitta bread", "biscote | rusk",
    ],
    "grains": [
        "arroz | rice", "arroz bomba | bomba rice", "arroz integral | brown rice",
        "arroz basmati | basmati rice", "arroz para risotto | risotto rice | arroz arborio",
        "lenteja | lentil", "garbanzo | chickpea", "alubia | bean | judía blanca | judión",
        "alubia roja | red bean", "alubia pinta | pinto bean", "soja texturizada | textured soy",
        "espagueti | spaghetti | spaghetti", "macarrón | macaroni", "tallarín | tagliatelle",
        "fideo | noodle", "fideo fino | vermicelli", "lasaña | lasagne sheet | placa de lasaña",
        "canelón | cannelloni", "pasta | pasta", "tortellini | tortellini",
        "cuscús | couscous", "quinoa | quinoa", "bulgur | bulgur", "trigo | wheat",
        "avena | oats | copos de avena", "harina | flour | harina de trigo",
        "harina de fuerza | strong flour", "harina integral | wholemeal flour",
        "maicena | cornflour | harina de maíz", "sémola | semolina", "polenta | polenta",
        "tapioca | tapioca",
    ],
    "pantry": [
        "tomate triturado | crushed tomato", "tomate frito | tomato sauce",
        "tomate concentrado | tomato paste", "atún en lata | tinned tuna",
        "sardina en lata | tinned sardine", "anchoa | anchovy fillet",
        "mejillón en escabeche | pickled mussels", "berberecho en lata | tinned cockles",
        "pimiento del piquillo | piquillo pepper", "garbanzo cocido | cooked chickpeas",
        "lenteja cocida | cooked lentils", "alubia cocida | cooked beans",
        "maíz en lata | tinned sweetcorn", "aceituna | olive", "alcaparra | caper",
        "pepinillo | gherkin", "caldo de pollo | chicken stock",
        "caldo de verduras | vegetable stock",
        "caldo de pescado | fish stock", "caldo de carne | beef stock",
        "pastilla de caldo | stock cube",
        "leche de coco | coconut milk", "leche evaporada | evaporated milk",
        "leche condensada | condensed milk", "almendra | almond", "nuez | walnut",
        "piñón | pine nut", "pistacho | pistachio", "cacahuete | peanut", "anacardo | cashew",
        "pasa | raisin", "orejón | dried apricot", "dátil | date", "ciruela pasa | prune",
        "castaña | chestnut", "almendra molida | ground almond", "semilla de chía | chia seed",
        "mermelada | jam", "miel | honey", "sirope de arce | maple syrup",
        "cacao en polvo | cocoa powder",
        "café | coffee", "té | tea", "infusión | herbal tea", "cereales | cereal",
        "galleta | biscuit",
    ],
    "spices": [
        "levadura | yeast | levadura química | levadura en polvo",
        "levadura fresca | fresh yeast | levadura de panadería",
        "bicarbonato | bicarbonate of soda", "gelatina | gelatine | gelatina en hojas",
        "agar-agar | agar", "caldo en polvo | stock powder",
    ],
    "oils": [
        "aceite de oliva | olive oil | aceite de oliva virgen extra | aove",
        "aceite de girasol | sunflower oil", "aceite | oil", "vinagre | vinegar",
        "vinagre de jerez | sherry vinegar", "vinagre de módena | balsamic vinegar",
        "vinagre de manzana | cider vinegar", "mayonesa | mayonnaise", "kétchup | ketchup",
        "salsa barbacoa | barbecue sauce", "salsa de tomate | tomato ketchup sauce",
        "alioli | aioli", "salsa brava | brava sauce", "salsa de ostras | oyster sauce",
        "salsa teriyaki | teriyaki sauce", "salsa rosa | cocktail sauce",
    ],
    "frozen": [
        "guisante congelado | frozen peas", "espinaca congelada | frozen spinach",
        "verdura congelada | frozen vegetables", "gamba congelada | frozen prawns",
        "langostino congelado | frozen king prawns", "calamar congelado | frozen squid",
        "masa congelada | frozen dough", "helado | ice cream", "hielo | ice",
        "patata congelada | frozen chips", "pizza congelada | frozen pizza",
        "croqueta congelada | frozen croquettes", "fruta congelada | frozen fruit",
    ],
    "drinks": [
        "agua mineral | mineral water", "agua con gas | sparkling water", "zumo | juice",
        "zumo de naranja | orange juice", "refresco | soft drink", "cerveza | beer",
        "vino tinto | red wine", "vino blanco | white wine", "vino rosado | rosé wine",
        "cava | cava", "vino de jerez | sherry | fino | vino fino", "brandy | brandy | coñac",
        "ron | rum", "whisky | whisky", "sidra | cider", "vermut | vermouth", "licor | liqueur",
    ],
    "sweets": [
        "azúcar | sugar | azúcar blanco", "azúcar glas | icing sugar",
        "chocolate | chocolate", "chocolate negro | dark chocolate",
        "chocolate para fundir | cooking chocolate | chocolate fondant",
        "pepitas de chocolate | chocolate chips", "cacao | cocoa", "fideos de colores | sprinkles",
        "fondant | fondant", "gelatina de sabores | jelly", "nata montada | whipped cream",
        "caramelo líquido | caramel syrup", "dulce de leche | dulce de leche",
        "crema de cacao | chocolate spread", "turrón | turrón", "mazapán | marzipan",
        "polvorón | polvorón", "bizcocho de soletilla | ladyfinger | soletilla",
        "almíbar | syrup", "confitura | preserve", "fruta confitada | candied fruit",
        "azúcar invertido | invert sugar",
    ],
    "other": [
        "papel de horno | baking paper | papel vegetal", "papel de aluminio | aluminium foil",
        "film transparente | cling film", "servilleta | napkin", "palillo | toothpick",
    ],
}  # fmt: skip
