"""Spice zone (approved in session 4): catalogue by family, general equivalence rules,
substitutions and blend compositions. Source: 02 - Producto / Categorías, especias y vinos.

Ingredient names are the normalised catalogue names: lowercase, singular.
"""

# family code -> [(name, name_en, aliases)]
SPICES = {
    "herbs": [
        ("perejil", "parsley", None),
        ("cilantro fresco", "coriander leaf", "cilantro"),
        ("albahaca", "basil", "albahaca fresca"),
        ("orégano", "oregano", None),
        ("tomillo", "thyme", None),
        ("romero", "rosemary", None),
        ("laurel", "bay leaf", "hoja de laurel"),
        ("menta", "mint", "hierbabuena"),
        ("eneldo", "dill", None),
        ("estragón", "tarragon", None),
        ("cebollino", "chives", None),
        ("salvia", "sage", None),
        ("mejorana", "marjoram", None),
        ("ajedrea", "savory", None),
        ("perifollo", "chervil", None),
        ("hojas de hinojo", "fennel fronds", "hinojo fresco"),
        ("hierba limón", "lemongrass", "citronela"),
        ("hojas de lima kaffir", "kaffir lime leaves", "lima kaffir"),
        ("hojas de curry", "curry leaves", None),
        ("epazote", "epazote", None),
    ],
    "seeds": [
        ("comino", "cumin", None),
        ("cilantro en grano", "coriander seed", "semillas de cilantro"),
        ("hinojo en grano", "fennel seed", "semillas de hinojo"),
        ("anís", "aniseed", "matalahúva, anís en grano"),
        ("anís estrellado", "star anise", None),
        ("semillas de mostaza", "mustard seed", "mostaza en grano"),
        ("sésamo", "sesame", "ajonjolí"),
        ("alcaravea", "caraway", None),
        ("nigella", "nigella", "comino negro"),
        ("fenogreco", "fenugreek", "alholva"),
        ("semillas de amapola", "poppy seed", "amapola"),
        ("cardamomo", "green cardamom", "cardamomo verde"),
        ("cardamomo negro", "black cardamom", None),
        ("semillas de apio", "celery seed", None),
        ("enebro", "juniper berries", "bayas de enebro"),
    ],
    "barks_roots_flowers": [
        ("canela", "cinnamon", "canela en rama, canela molida"),
        ("casia", "cassia", None),
        ("jengibre molido", "ground ginger", "jengibre en polvo"),
        ("cúrcuma", "turmeric", None),
        ("galanga", "galangal", None),
        ("regaliz", "liquorice root", None),
        ("azafrán", "saffron", None),
        ("clavo", "cloves", "clavo de olor"),
        ("nuez moscada", "nutmeg", None),
        ("macis", "mace", None),
        ("vainilla", "vanilla", "extracto de vainilla, vaina de vainilla"),
        ("lavanda", "lavender", None),
        ("agua de azahar", "orange-blossom water", None),
        ("agua de rosas", "rose water", None),
        ("zumaque", "sumac", None),
    ],
    "peppers_chillies": [
        ("pimienta negra", "black pepper", None),
        ("pimienta blanca", "white pepper", None),
        ("pimienta verde", "green pepper", None),
        ("pimienta rosa", "pink pepper", None),
        ("pimienta de jamaica", "allspice", "malagueta"),
        ("pimienta de sichuan", "Sichuan pepper", None),
        ("pimienta larga", "long pepper", None),
        ("cayena", "cayenne", "pimienta de cayena, cayena molida"),
        ("guindilla seca", "dried chilli", "chile seco"),
        ("copos de guindilla", "chilli flakes", "guindilla en copos"),
        ("ñora", "ñora pepper", None),
        ("pimiento choricero", "choricero pepper", None),
        ("chile chipotle", "chipotle", "chipotle"),
        ("chile ancho", "ancho chilli", None),
        ("chile de árbol", "chile de árbol", None),
        ("chile habanero", "habanero", "habanero"),
        ("gochugaru", "Korean chilli flakes", None),
        ("harissa", "harissa", "pasta de harissa"),
        ("wasabi", "wasabi", None),
        ("rábano picante", "horseradish", None),
    ],
    "paprikas": [
        ("pimentón dulce", "sweet paprika", "pimentón"),
        ("pimentón picante", "hot paprika", None),
        ("pimentón agridulce", "bittersweet paprika", None),
        ("pimentón de la vera", "smoked paprika", "pimentón ahumado"),
        ("pimentón de murcia", "Murcia paprika", None),
    ],
    "blends": [
        ("curry en polvo", "curry powder", "curry"),
        ("garam masala", "garam masala", None),
        ("ras el hanout", "ras el hanout", None),
        ("cinco especias chinas", "Chinese five spice", "cinco especias"),
        ("hierbas provenzales", "herbes de Provence", None),
        ("za'atar", "za'atar", "zatar"),
        ("baharat", "baharat", None),
        ("tandoori masala", "tandoori masala", None),
        ("shichimi togarashi", "shichimi togarashi", "togarashi"),
        ("chile en polvo", "chili powder (Tex-Mex)", "chili en polvo"),
        ("cajún", "Cajun seasoning", "mezcla cajún"),
        ("jerk", "jerk seasoning", "mezcla jerk"),
        (
            "adobo para pinchitos",
            "Andalusian pinchito spice mix",
            "especias para pinchitos morunos",
        ),
        ("adobo para carne y pescado", "Cádiz-style adobo", "adobo"),
        ("mixed spice", "mixed spice", None),
        ("pumpkin spice", "pumpkin spice", None),
        ("quatre épices", "quatre épices", "cuatro especias"),
        ("dukkah", "dukkah", None),
        ("berberé", "berbere", None),
        ("especias para caldereta", "caldereta spice mix", "mezcla para caldereta"),
    ],
    "salts_seasonings": [
        ("colorante alimentario", "food colouring (paella)", "colorante, colorante de paella"),
        ("sal en escamas", "flaky salt", None),
        ("sal ahumada", "smoked salt", None),
        ("sal de apio", "celery salt", None),
        ("sal de ajo", "garlic salt", None),
        ("ajo en polvo", "garlic powder", "ajo granulado"),
        ("cebolla en polvo", "onion powder", None),
        ("glutamato", "MSG", "umami"),
        ("alga kombu", "kombu", "kombu"),
        ("alga nori", "nori", "nori"),
        ("bonito seco", "katsuobushi", "katsuobushi"),
        ("miso", "miso", None),
        ("salsa de soja", "soy sauce", "soja"),
        ("salsa de pescado", "fish sauce", None),
        ("tamarindo", "tamarind", "pasta de tamarindo"),
        ("cáscara de cítricos seca", "dried citrus peel", "cáscara de mandarina seca"),
        ("amchur", "amchur (mango powder)", "mango en polvo"),
        ("asafétida", "asafoetida", None),
    ],
}

# Non-spice ingredients the substitution table needs, with their shopping section
FRESH_INGREDIENTS = [
    ("ajo", "garlic", "ajo fresco, diente de ajo", "produce"),
    ("cebolla", "onion", "cebolla fresca", "produce"),
    ("jengibre fresco", "fresh ginger", "jengibre", "produce"),
    ("guindilla fresca", "fresh chilli", "guindilla", "produce"),
    ("limón", "lemon", "ralladura de limón", "produce"),
    ("lima", "lime", "ralladura de lima", "produce"),
    ("naranja", "orange", "ralladura de naranja", "produce"),
    ("cebolleta", "spring onion", None, "produce"),
    ("chalota", "shallot", None, "produce"),
    ("apio", "celery", None, "produce"),
    ("puerro", "leek", None, "produce"),
    ("pesto", "pesto", None, "oils"),
    ("mostaza", "prepared mustard", "mostaza preparada", "oils"),
    ("mostaza en polvo", "mustard powder", None, "spices"),
    ("tabasco", "hot sauce", "salsa picante", "oils"),
    ("sriracha", "sriracha", "sambal oelek", "oils"),
    ("tahini", "tahini", None, "oils"),
    ("tamari", "tamari", None, "oils"),
    ("salsa worcestershire", "Worcestershire sauce", "salsa perrins", "oils"),
    ("pasta de anchoas", "anchovy paste", None, "pantry"),
    ("licor de anís", "anise liqueur", None, "drinks"),
    ("ginebra", "gin", None, "drinks"),
    ("licor de naranja", "orange liqueur", "cointreau, triple seco", "drinks"),
    ("azúcar avainillado", "vanilla sugar", None, "sweets"),
    ("esencia de almendra", "almond essence", None, "sweets"),
    ("humo líquido", "liquid smoke", None, "oils"),
    ("chipotle en adobo", "chipotle in adobo", None, "pantry"),
    ("cártamo", "safflower", "azafrán bastardo", "spices"),
    ("aceite de sésamo", "sesame oil", None, "oils"),
    ("pipas de girasol", "sunflower seeds", None, "pantry"),
    ("avellanas", "hazelnuts", None, "pantry"),
    ("azúcar moreno", "brown sugar", None, "sweets"),
    ("sal", "salt", None, "spices"),
]

# (situation_es, situation_en, equivalence_es, equivalence_en, note_es, note_en)
EQUIVALENCE_RULES = [
    (
        "Hierba fresca ⇄ seca",
        "Fresh herb ⇄ dried",
        "1 cucharada de fresca = 1 cucharadita de seca (3 : 1)",
        "1 tablespoon fresh = 1 teaspoon dried (3 : 1)",
        "La seca se añade al principio de la cocción; la fresca, al final",
        "Add dried at the start of cooking; fresh at the end",
    ),
    (
        "Especia entera → molida",
        "Whole spice → ground",
        "1 cucharadita entera ≈ ¾ de cucharadita molida",
        "1 teaspoon whole ≈ ¾ teaspoon ground",
        "La molida pierde aroma en 6 meses; la entera aguanta 2–3 años",
        "Ground loses aroma in 6 months; whole keeps 2–3 years",
    ),
    (
        "Ajo",
        "Garlic",
        "1 diente = ¼ cucharadita de ajo en polvo = ½ cucharadita de ajo granulado",
        "1 clove = ¼ teaspoon garlic powder = ½ teaspoon granulated garlic",
        None,
        None,
    ),
    (
        "Cebolla",
        "Onion",
        "1 cebolla mediana = 1 cucharada de cebolla en polvo",
        "1 medium onion = 1 tablespoon onion powder",
        None,
        None,
    ),
    (
        "Jengibre",
        "Ginger",
        "1 cucharada de fresco rallado = ¼ cucharadita de jengibre molido",
        "1 tablespoon grated fresh = ¼ teaspoon ground",
        "El molido es más picante y menos fresco",
        "Ground is hotter and less fresh",
    ),
    (
        "Guindilla fresca → seca",
        "Fresh chilli → dried",
        "1 guindilla fresca ≈ ½ cucharadita de copos ≈ ¼ cucharadita de cayena molida",
        "1 fresh chilli ≈ ½ teaspoon flakes ≈ ¼ teaspoon cayenne",
        None,
        None,
    ),
    (
        "Medidas",
        "Measures",
        "1 cucharadita (cdta) = 5 ml · 1 cucharada (cda) = 15 ml · 1 pizca ≈ ⅛ cdta",
        "1 teaspoon (tsp) = 5 ml · 1 tablespoon (tbsp) = 15 ml · 1 pinch ≈ ⅛ tsp",
        "La app usa siempre estas abreviaturas",
        "The app always uses these abbreviations",
    ),
]

# missing ingredient -> [(substitute_es, substitute_en, ratio, note_es, note_en, linked_name)]
# ratio is per 1 tsp of the missing ingredient unless stated. linked_name: catalogue ingredient
# when the substitute is a single one (None for combinations).
SUBSTITUTIONS = {
    "albahaca": [
        ("Orégano fresco", "Fresh oregano", "1 : 1", "Más terroso", "Earthier", "orégano"),
        (
            "Albahaca seca",
            "Dried basil",
            "1 cda fresca = 1 cdta seca",
            "Pierde el frescor; añadir al final",
            "Loses freshness; add at the end",
            None,
        ),
        (
            "Pesto",
            "Pesto",
            "1 cda de pesto por 2 cdas de hojas",
            "Solo en pastas y salsas",
            "Only in pasta and sauces",
            "pesto",
        ),
    ],
    "orégano": [
        (
            "Mejorana",
            "Marjoram",
            "1 : 1½",
            "La mejorana es más suave y dulce",
            "Marjoram is milder and sweeter",
            "mejorana",
        ),
        (
            "Tomillo",
            "Thyme",
            "1 : 1",
            "Buena en carnes y tomate",
            "Good with meat and tomato",
            "tomillo",
        ),
        (
            "Hierbas provenzales",
            "Herbes de Provence",
            "1 : 1",
            "Cambia el aroma general",
            "Changes the overall aroma",
            "hierbas provenzales",
        ),
    ],
    "tomillo": [
        ("Orégano o mejorana", "Oregano or marjoram", "1 : 1", None, None, None),
        (
            "Romero",
            "Rosemary",
            "1 : ½",
            "Más fuerte, usar la mitad",
            "Stronger, use half",
            "romero",
        ),
        ("Ajedrea", "Savory", "1 : 1", "Muy parecida", "Very similar", "ajedrea"),
    ],
    "romero": [
        ("Tomillo", "Thyme", "1 : 1", "Más suave", "Milder", "tomillo"),
        (
            "Salvia",
            "Sage",
            "1 : ½",
            "En asados de cerdo y aves",
            "In pork and poultry roasts",
            "salvia",
        ),
    ],
    "laurel": [
        (
            "Tomillo",
            "Thyme",
            "1 hoja = ¼ cdta",
            "Aporta el fondo aromático",
            "Gives the aromatic base",
            "tomillo",
        ),
        (
            "Nada",
            "Nothing",
            None,
            "El laurel se puede omitir sin arruinar un guiso",
            "Bay can be left out without ruining a stew",
            None,
        ),
    ],
    "perejil": [
        (
            "Cilantro fresco",
            "Fresh coriander",
            "1 : 1",
            "Cambia mucho el sabor: solo si la receta acepta cilantro",
            "Very different flavour: only if the recipe takes coriander",
            "cilantro fresco",
        ),
        ("Perifollo", "Chervil", "1 : 1", "Muy fiel", "Very faithful", "perifollo"),
        (
            "Cebollino",
            "Chives",
            "1 : 1",
            "Aporta un toque de cebolla",
            "Adds an onion note",
            "cebollino",
        ),
    ],
    "cilantro fresco": [
        (
            "Perejil + un poco de ralladura de lima",
            "Parsley + a little lime zest",
            "1 : 1",
            "El perejil da el color; la lima, el frescor",
            "Parsley gives colour; lime, freshness",
            None,
        ),
        ("Hojas de apio", "Celery leaves", "1 : 1", None, None, "apio"),
        (
            "Cilantro en grano molido",
            "Ground coriander seed",
            "1 cda fresco = ¼ cdta molido",
            "Sabor distinto (cálido, cítrico) pero de la misma planta",
            "Different flavour (warm, citrusy) but same plant",
            "cilantro en grano",
        ),
    ],
    "estragón": [
        ("Perifollo", "Chervil", "1 : 1", None, None, "perifollo"),
        (
            "Hinojo en grano o anís (una pizca)",
            "Fennel seed or aniseed (a pinch)",
            "1 : ¼",
            "Solo por el matiz anisado",
            "Only for the anise note",
            None,
        ),
    ],
    "eneldo": [
        (
            "Hojas de hinojo",
            "Fennel fronds",
            "1 : 1",
            "Muy parecido",
            "Very similar",
            "hojas de hinojo",
        ),
        ("Estragón", "Tarragon", "1 : 1", None, None, "estragón"),
    ],
    "menta": [
        ("Albahaca", "Basil", "1 : 1", "En platos salados", "In savoury dishes", "albahaca"),
        (
            "Extracto de menta",
            "Mint extract",
            "1 cda fresca = ⅛ cdta extracto",
            "Solo en dulces",
            "Only in sweets",
            None,
        ),
    ],
    "salvia": [
        ("Mejorana o romero", "Marjoram or rosemary", "1 : 1 / 1 : ½", None, None, None),
        ("Tomillo", "Thyme", "1 : 1", None, None, "tomillo"),
    ],
    "cebollino": [
        (
            "Parte verde de cebolleta, picada fina",
            "Green part of spring onion, finely chopped",
            "1 : 1",
            None,
            None,
            "cebolleta",
        ),
        (
            "Cebolla en polvo",
            "Onion powder",
            "1 cda = ¼ cdta",
            "Sin el color verde",
            "Without the green colour",
            "cebolla en polvo",
        ),
    ],
    "comino": [
        (
            "Cilantro en grano molido",
            "Ground coriander seed",
            "1 : 1",
            "Más cítrico, menos terroso",
            "More citrusy, less earthy",
            "cilantro en grano",
        ),
        (
            "Alcaravea",
            "Caraway",
            "1 : ½",
            "Misma familia, sabor más fuerte",
            "Same family, stronger flavour",
            "alcaravea",
        ),
        (
            "Chile en polvo tex-mex",
            "Tex-Mex chili powder",
            "1 : 1",
            "Ya lleva comino",
            "Already contains cumin",
            "chile en polvo",
        ),
    ],
    "cilantro en grano": [
        ("Comino", "Cumin", "1 : ½", None, None, "comino"),
        ("Alcaravea", "Caraway", "1 : ½", None, None, "alcaravea"),
        ("Hinojo en grano", "Fennel seed", "1 : 1", None, None, "hinojo en grano"),
    ],
    "hinojo en grano": [
        ("Anís (matalahúva)", "Aniseed", "1 : ½", "Más dulce", "Sweeter", "anís"),
        ("Anís estrellado molido", "Ground star anise", "1 : ½", None, None, "anís estrellado"),
        ("Alcaravea", "Caraway", "1 : 1", None, None, "alcaravea"),
    ],
    "anís": [
        ("Hinojo en grano", "Fennel seed", "1 : 1", None, None, "hinojo en grano"),
        (
            "Anís estrellado",
            "Star anise",
            "1 : ½",
            "Más intenso",
            "More intense",
            "anís estrellado",
        ),
        (
            "Licor de anís",
            "Anise liqueur",
            "1 cdta = 1 cda de licor",
            "En dulces (roscos, pestiños)",
            "In sweets (roscos, pestiños)",
            "licor de anís",
        ),
    ],
    "anís estrellado": [
        ("Anís en grano", "Aniseed", "1 : 1½", "Más suave", "Milder", "anís"),
        (
            "Cinco especias chinas",
            "Chinese five spice",
            "1 : 1",
            "Ya lo contiene",
            "Already contains it",
            "cinco especias chinas",
        ),
    ],
    "semillas de mostaza": [
        ("Mostaza en polvo", "Mustard powder", "1 : ½", None, None, "mostaza en polvo"),
        (
            "Mostaza preparada",
            "Prepared mustard",
            "1 cdta = 1 cda",
            "Añade vinagre",
            "Adds vinegar",
            "mostaza",
        ),
        (
            "Rábano picante rallado",
            "Grated horseradish",
            "1 : ½",
            "Solo por el picante",
            "Only for the heat",
            "rábano picante",
        ),
    ],
    "sésamo": [
        (
            "Pipas de girasol o almendra picada",
            "Sunflower seeds or chopped almond",
            "1 : 1",
            "Por la textura",
            "For the texture",
            "pipas de girasol",
        ),
        (
            "Aceite de sésamo (para el sabor)",
            "Sesame oil (for the flavour)",
            "1 cda semillas = ½ cdta aceite",
            None,
            None,
            "aceite de sésamo",
        ),
    ],
    "alcaravea": [
        ("Comino", "Cumin", "1 : 1", None, None, "comino"),
        ("Hinojo en grano", "Fennel seed", "1 : 1", None, None, "hinojo en grano"),
        ("Anís", "Aniseed", "1 : ½", None, None, "anís"),
    ],
    "fenogreco": [
        (
            "Semillas de mostaza + una pizca de jarabe de arce",
            "Mustard seeds + a pinch of maple syrup",
            "1 : 1",
            "Amargo + dulce, imita bastante",
            "Bitter + sweet, quite close",
            None,
        ),
        (
            "Hojas de curry",
            "Curry leaves",
            None,
            "Solo en platos indios",
            "Only in Indian dishes",
            "hojas de curry",
        ),
        (
            "Omitir",
            "Leave out",
            None,
            "En un curry con muchas especias no se nota",
            "In a curry with many spices it goes unnoticed",
            None,
        ),
    ],
    "cardamomo": [
        (
            "Canela + nuez moscada, mitad y mitad",
            "Cinnamon + nutmeg, half and half",
            "1 : 1",
            "Lo más parecido en dulces",
            "The closest in sweets",
            None,
        ),
        (
            "Jengibre molido",
            "Ground ginger",
            "1 : 1",
            "En platos salados",
            "In savoury dishes",
            "jengibre molido",
        ),
        (
            "Cilantro en grano + una pizca de clavo",
            "Coriander seed + a pinch of cloves",
            "1 : 1",
            None,
            None,
            None,
        ),
    ],
    "enebro": [
        ("Romero", "Rosemary", "1 : ½", "En caza y cerdo", "In game and pork", "romero"),
        (
            "Un chorrito de ginebra",
            "A splash of gin",
            "3 bayas = 1 cda de ginebra",
            "La ginebra es enebro",
            "Gin is juniper",
            "ginebra",
        ),
    ],
    "canela": [
        (
            "Casia",
            "Cassia",
            "1 : 1",
            "Es lo que suele venderse como canela; más fuerte",
            "What is usually sold as cinnamon; stronger",
            "casia",
        ),
        ("Nuez moscada o pimienta de Jamaica", "Nutmeg or allspice", "1 : ¼", None, None, None),
        (
            "Mixed spice o pumpkin spice",
            "Mixed spice or pumpkin spice",
            "1 : 1",
            "Ya la contienen",
            "Already contain it",
            None,
        ),
    ],
    "jengibre molido": [
        (
            "Pimienta de Jamaica, canela, macis o nuez moscada",
            "Allspice, cinnamon, mace or nutmeg",
            "1 : 1",
            "En dulces; se pierde el picante",
            "In sweets; the heat is lost",
            None,
        ),
        (
            "Jengibre fresco rallado",
            "Grated fresh ginger",
            "¼ cdta molido = 1 cda fresco",
            None,
            None,
            "jengibre fresco",
        ),
        (
            "Galanga",
            "Galangal",
            "1 : 1",
            "Más cítrica y pinosa (cocina tailandesa)",
            "More citrusy and piney (Thai cooking)",
            "galanga",
        ),
    ],
    "jengibre fresco": [
        (
            "Jengibre molido",
            "Ground ginger",
            "1 cda fresco = ¼ cdta molido",
            None,
            None,
            "jengibre molido",
        ),
        (
            "Jengibre confitado, lavado",
            "Candied ginger, rinsed",
            "1 : 1",
            "Enjuagar el azúcar",
            "Rinse off the sugar",
            None,
        ),
        ("Galanga", "Galangal", "1 : 1", None, None, "galanga"),
    ],
    "cúrcuma": [
        (
            "Azafrán (solo por el color)",
            "Saffron (colour only)",
            "1 cdta = 1 pizca de azafrán",
            "El azafrán es mucho más caro; usar solo si sobra",
            "Saffron is far more expensive; only if you have spare",
            "azafrán",
        ),
        (
            "Curry en polvo",
            "Curry powder",
            "1 : 1",
            "Ya la lleva; añade otras especias",
            "Contains it; adds other spices",
            "curry en polvo",
        ),
        (
            "Colorante alimentario amarillo",
            "Yellow food colouring",
            "1 : 1",
            "Solo color, ningún sabor",
            "Colour only, no flavour",
            "colorante alimentario",
        ),
        (
            "Jengibre molido + pimentón (color)",
            "Ground ginger + paprika (colour)",
            "1 : ½ + ½",
            "Aproximación",
            "Approximation",
            None,
        ),
    ],
    "colorante alimentario": [
        (
            "Cúrcuma",
            "Turmeric",
            "1 pizca = ¼ cdta",
            "Da el mismo amarillo y un punto de sabor terroso",
            "Same yellow with a slightly earthy taste",
            "cúrcuma",
        ),
        (
            "Azafrán",
            "Saffron",
            "1 pizca = 6–8 hebras",
            "El color y el sabor auténticos del arroz; infusionar antes en caldo caliente",
            "The authentic colour and taste for rice; steep in hot stock first",
            "azafrán",
        ),
        (
            "Pimentón dulce",
            "Sweet paprika",
            "1 : 1",
            "Color más rojizo",
            "Redder colour",
            "pimentón dulce",
        ),
    ],
    "galanga": [
        (
            "Jengibre fresco",
            "Fresh ginger",
            "1 : 1",
            "Menos cítrico; añadir una pizca de pimienta",
            "Less citrusy; add a pinch of pepper",
            "jengibre fresco",
        ),
    ],
    "azafrán": [
        (
            "Cúrcuma",
            "Turmeric",
            "1 pizca = ¼ cdta",
            "Da el color, no el sabor",
            "Gives the colour, not the flavour",
            "cúrcuma",
        ),
        (
            'Colorante alimentario ("el de la paella")',
            "Paella food colouring",
            "1 pizca = ¼ cdta",
            "Solo color",
            "Colour only",
            "colorante alimentario",
        ),
        (
            "Pimentón dulce + cúrcuma",
            "Sweet paprika + turmeric",
            "mitad y mitad",
            "Color más rojizo",
            "Redder colour",
            None,
        ),
        (
            "Cártamo (azafrán bastardo)",
            "Safflower",
            "1 : 2",
            "Color, poco sabor",
            "Colour, little flavour",
            "cártamo",
        ),
    ],
    "clavo": [
        (
            "Pimienta de Jamaica",
            "Allspice",
            "1 : 1",
            "Muy parecido",
            "Very similar",
            "pimienta de jamaica",
        ),
        ("Nuez moscada o canela", "Nutmeg or cinnamon", "1 : 1", None, None, None),
        (
            "Cinco especias chinas",
            "Chinese five spice",
            "1 : 1",
            None,
            None,
            "cinco especias chinas",
        ),
    ],
    "nuez moscada": [
        (
            "Macis",
            "Mace",
            "1 : 1",
            "Es la envoltura de la nuez moscada: el sustituto perfecto",
            "The nutmeg's own covering: the perfect substitute",
            "macis",
        ),
        ("Pimienta de Jamaica", "Allspice", "1 : 1", None, None, "pimienta de jamaica"),
        ("Canela o clavo", "Cinnamon or cloves", "1 : ½", None, None, None),
        ("Jengibre molido", "Ground ginger", "1 : 1", "En dulces", "In sweets", "jengibre molido"),
    ],
    "macis": [
        ("Nuez moscada", "Nutmeg", "1 : 1", None, None, "nuez moscada"),
        (
            "Pimienta de Jamaica + una pizca de canela",
            "Allspice + a pinch of cinnamon",
            "1 : 1",
            None,
            None,
            None,
        ),
    ],
    "vainilla": [
        (
            "Vaina de vainilla",
            "Vanilla pod",
            "1 cdta extracto = ⅓ de vaina",
            "Raspar las semillas",
            "Scrape out the seeds",
            None,
        ),
        (
            "Azúcar avainillado",
            "Vanilla sugar",
            "1 cdta extracto = 1 sobre (8 g)",
            "Reducir 1 cdta de azúcar",
            "Reduce sugar by 1 tsp",
            "azúcar avainillado",
        ),
        (
            "Esencia de almendra",
            "Almond essence",
            "1 : ½",
            "Cambia el aroma",
            "Changes the aroma",
            "esencia de almendra",
        ),
        (
            "Ron, brandy o licor de café",
            "Rum, brandy or coffee liqueur",
            "1 : 1",
            "En bizcochos y cremas",
            "In sponges and creams",
            None,
        ),
        (
            "Ralladura de naranja o limón",
            "Orange or lemon zest",
            "1 : 1",
            "En bizcochos españoles es lo tradicional",
            "Traditional in Spanish sponges",
            None,
        ),
    ],
    "agua de azahar": [
        (
            "Ralladura de naranja",
            "Orange zest",
            "1 cda = 1 cdta de ralladura",
            "En roscón y torrijas",
            "In roscón and torrijas",
            "naranja",
        ),
        (
            "Agua de rosas",
            "Rose water",
            "1 : ½",
            "Aroma distinto",
            "Different aroma",
            "agua de rosas",
        ),
        (
            "Licor de naranja (Cointreau, triple seco)",
            "Orange liqueur (Cointreau, triple sec)",
            "1 : 1",
            None,
            None,
            "licor de naranja",
        ),
    ],
    "agua de rosas": [
        ("Agua de azahar", "Orange-blossom water", "1 : 1", None, None, "agua de azahar"),
        ("Extracto de vainilla", "Vanilla extract", "1 : ½", None, None, "vainilla"),
    ],
    "lavanda": [
        ("Romero", "Rosemary", "1 : ½", "En salados", "In savoury dishes", "romero"),
        (
            "Hierbas provenzales",
            "Herbes de Provence",
            "1 : 1",
            "Suele llevarla",
            "Usually contains it",
            "hierbas provenzales",
        ),
    ],
    "zumaque": [
        (
            "Ralladura de limón + una pizca de sal",
            "Lemon zest + a pinch of salt",
            "1 cdta = ½ cdta ralladura + pizca sal",
            "Aporta la acidez; no el color",
            "Gives the acidity, not the colour",
            None,
        ),
        (
            "Vinagre de vino tinto (unas gotas)",
            "Red wine vinegar (a few drops)",
            None,
            None,
            None,
            None,
        ),
        ("Amchur", "Amchur", "1 : 1", None, None, "amchur"),
    ],
    "pimienta negra": [
        (
            "Pimienta blanca",
            "White pepper",
            "1 : 1",
            "Más suave y terrosa; ideal en salsas blancas",
            "Milder and earthier; ideal in white sauces",
            "pimienta blanca",
        ),
        ("Pimienta verde", "Green pepper", "1 : 1", "Más fresca", "Fresher", "pimienta verde"),
        (
            "Cayena",
            "Cayenne",
            "1 : ⅛",
            "Solo picante, mucho más fuerte",
            "Heat only, much stronger",
            "cayena",
        ),
        (
            "Pimienta de Jamaica",
            "Allspice",
            "1 : 1",
            "Dulce y cálida",
            "Sweet and warm",
            "pimienta de jamaica",
        ),
    ],
    "pimienta blanca": [
        (
            "Pimienta negra",
            "Black pepper",
            "1 : 1",
            "Se ven las motas oscuras",
            "Dark specks will show",
            "pimienta negra",
        ),
    ],
    "pimienta de jamaica": [
        (
            "Canela + clavo + nuez moscada, a partes iguales",
            "Cinnamon + cloves + nutmeg, equal parts",
            "1 : 1",
            "Es la mezcla clásica que la imita",
            "The classic mix that imitates it",
            None,
        ),
        ("Clavo", "Cloves", "1 : ½", None, None, "clavo"),
    ],
    "pimienta de sichuan": [
        (
            "Pimienta negra + ralladura de limón",
            "Black pepper + lemon zest",
            "1 : 1",
            "Falta el hormigueo característico",
            "The characteristic tingle is missing",
            None,
        ),
        (
            "Pimienta rosa + cilantro en grano",
            "Pink pepper + coriander seed",
            "1 : 1",
            None,
            None,
            None,
        ),
    ],
    "pimienta rosa": [
        (
            "Pimienta de Sichuan o granos de cilantro",
            "Sichuan pepper or coriander seed",
            "1 : 1",
            None,
            None,
            None,
        ),
        (
            "Pimienta negra (menos cantidad)",
            "Black pepper (less)",
            "1 : ½",
            None,
            None,
            "pimienta negra",
        ),
    ],
    "cayena": [
        ("Copos de guindilla", "Chilli flakes", "1 : 1½", None, None, "copos de guindilla"),
        (
            "Guindilla fresca picada",
            "Chopped fresh chilli",
            "1 cdta = 1 guindilla",
            None,
            None,
            "guindilla fresca",
        ),
        (
            "Pimentón picante",
            "Hot paprika",
            "1 : 2",
            "Menos picante, más sabor",
            "Less heat, more flavour",
            "pimentón picante",
        ),
        (
            "Tabasco u otra salsa picante",
            "Tabasco or another hot sauce",
            "1 cdta = 1 cda de salsa",
            "Añade vinagre",
            "Adds vinegar",
            "tabasco",
        ),
        (
            "Chile en polvo",
            "Chili powder",
            "1 : 2",
            "Lleva comino y otras especias",
            "Contains cumin and other spices",
            "chile en polvo",
        ),
    ],
    "copos de guindilla": [
        ("Cayena", "Cayenne", "1 : ½", None, None, "cayena"),
        (
            "Guindilla seca desmenuzada",
            "Crumbled dried chilli",
            "1 : 1",
            None,
            None,
            "guindilla seca",
        ),
        (
            "Gochugaru",
            "Gochugaru",
            "1 : 1½",
            "Más suave y dulce",
            "Milder and sweeter",
            "gochugaru",
        ),
    ],
    "ñora": [
        (
            "Pimiento choricero",
            "Choricero pepper",
            "1 : 1",
            "Un poco más amargo",
            "Slightly more bitter",
            "pimiento choricero",
        ),
        (
            "Pimentón dulce (o ahumado)",
            "Sweet (or smoked) paprika",
            "1 ñora = 1 cdta de pimentón",
            "Lo más habitual en casa",
            "The usual choice at home",
            "pimentón dulce",
        ),
        (
            "Chile ancho",
            "Ancho chilli",
            "1 : 1",
            "Parecido (secos, dulces, sin picante)",
            "Similar (dried, sweet, no heat)",
            "chile ancho",
        ),
    ],
    "pimiento choricero": [
        ("Ñora", "Ñora pepper", "1 : 1", None, None, "ñora"),
        (
            "Pimentón dulce",
            "Sweet paprika",
            "1 pimiento = 1½ cdta",
            "Añadir un poco de tomate concentrado",
            "Add a little tomato purée",
            "pimentón dulce",
        ),
        ("Chile ancho", "Ancho chilli", "1 : 1", None, None, "chile ancho"),
    ],
    "chile chipotle": [
        (
            "Pimentón ahumado + cayena",
            "Smoked paprika + cayenne",
            "1 : 1 + ¼",
            "Humo + picante",
            "Smoke + heat",
            None,
        ),
        (
            "Chipotle en adobo (lata)",
            "Chipotle in adobo (tin)",
            "1 seco = 1 cdta de la pasta",
            None,
            None,
            "chipotle en adobo",
        ),
    ],
    "chile ancho": [
        ("Ñora o pimiento choricero", "Ñora or choricero pepper", "1 : 1", None, None, None),
        (
            "Pimentón dulce + una pizca de cacao",
            "Sweet paprika + a pinch of cocoa",
            "1 : 1",
            None,
            None,
            None,
        ),
    ],
    "gochugaru": [
        (
            "Copos de guindilla + pimentón dulce",
            "Chilli flakes + sweet paprika",
            "½ + ½",
            "Suaviza el picante",
            "Softens the heat",
            None,
        ),
        ("Cayena", "Cayenne", "1 : ⅓", None, None, "cayena"),
    ],
    "harissa": [
        (
            "Copos de guindilla + comino + ajo + aceite",
            "Chilli flakes + cumin + garlic + oil",
            None,
            "Se hace en 5 minutos",
            "Takes 5 minutes to make",
            None,
        ),
        (
            "Sriracha o sambal oelek",
            "Sriracha or sambal oelek",
            "1 : 1",
            "Menos aromática",
            "Less aromatic",
            "sriracha",
        ),
    ],
    "wasabi": [
        (
            "Rábano picante rallado o en pasta",
            "Grated horseradish or paste",
            "1 : 1",
            'Es lo que lleva casi todo el "wasabi" que se vende',
            'What most shop-bought "wasabi" is made of',
            "rábano picante",
        ),
        ("Mostaza inglesa fuerte", "Hot English mustard", "1 : 1", None, None, "mostaza"),
    ],
    "rábano picante": [
        ("Wasabi", "Wasabi", "1 : 1", None, None, "wasabi"),
        ("Mostaza en polvo", "Mustard powder", "1 : ½", None, None, "mostaza en polvo"),
    ],
    "pimentón dulce": [
        (
            "Pimentón de la Vera dulce",
            "Sweet smoked paprika",
            "1 : 1",
            "Añade humo",
            "Adds smoke",
            "pimentón de la vera",
        ),
        (
            "Ñora o choricero (pulpa)",
            "Ñora or choricero (flesh)",
            "1 cdta = 1 ñora",
            None,
            None,
            "ñora",
        ),
        (
            "Pimentón agridulce",
            "Bittersweet paprika",
            "1 : 1",
            "Ligeramente picante",
            "Slightly hot",
            "pimentón agridulce",
        ),
        ("Chile ancho molido", "Ground ancho chilli", "1 : 1", None, None, "chile ancho"),
    ],
    "pimentón picante": [
        ("Pimentón dulce + cayena", "Sweet paprika + cayenne", "1 : 1 + ⅛", None, None, None),
    ],
    "pimentón de la vera": [
        (
            "Pimentón dulce + unas gotas de humo líquido",
            "Sweet paprika + a few drops of liquid smoke",
            "1 : 1",
            None,
            None,
            None,
        ),
        (
            "Pimentón dulce + chipotle molido",
            "Sweet paprika + ground chipotle",
            "¾ + ¼",
            None,
            None,
            None,
        ),
        (
            "Pimentón dulce",
            "Sweet paprika",
            "1 : 1",
            "Se pierde el humo, pero el plato funciona",
            "The smoke is lost, but the dish works",
            "pimentón dulce",
        ),
    ],
    "ajo": [
        ("Ajo en polvo", "Garlic powder", "1 diente = ¼ cdta", None, None, "ajo en polvo"),
        ("Ajo granulado", "Granulated garlic", "1 diente = ½ cdta", None, None, "ajo en polvo"),
        (
            "Sal de ajo",
            "Garlic salt",
            "1 diente = ½ cdta",
            "Reducir la sal de la receta",
            "Reduce the salt in the recipe",
            "sal de ajo",
        ),
        (
            "Cebollino o ajete",
            "Chives or green garlic",
            "1 diente = 1 cda",
            "Más suave",
            "Milder",
            "cebollino",
        ),
        (
            "Asafétida",
            "Asafoetida",
            "1 diente = 1 pizca",
            "En cocina india; para quien no toma ajo",
            "In Indian cooking; for people who avoid garlic",
            "asafétida",
        ),
    ],
    "cebolla": [
        ("Cebolla en polvo", "Onion powder", "1 cebolla = 1 cda", None, None, "cebolla en polvo"),
        ("Cebolleta o puerro", "Spring onion or leek", "1 : 1", "Más suave", "Milder", None),
        ("Chalota", "Shallot", "1 cebolla = 3 chalotas", "Más fina", "Finer", "chalota"),
    ],
    "hierba limón": [
        (
            "Ralladura de limón",
            "Lemon zest",
            "1 tallo = 1 cdta de ralladura",
            "Sin la nota herbal",
            "Without the herbal note",
            "limón",
        ),
        (
            "Ralladura de lima + una pizca de jengibre",
            "Lime zest + a pinch of ginger",
            "1 tallo = 1 cdta",
            None,
            None,
            None,
        ),
        (
            "Hojas de lima kaffir",
            "Kaffir lime leaves",
            "1 tallo = 2 hojas",
            None,
            None,
            "hojas de lima kaffir",
        ),
    ],
    "hojas de lima kaffir": [
        ("Ralladura de lima", "Lime zest", "2 hojas = ½ cdta", None, None, "lima"),
        (
            "Hoja de laurel + ralladura de lima",
            "Bay leaf + lime zest",
            "2 hojas = 1 laurel + ¼ cdta",
            None,
            None,
            None,
        ),
    ],
    "hojas de curry": [
        (
            "Ralladura de lima + albahaca",
            "Lime zest + basil",
            None,
            "Aproximación; a menudo se omiten",
            "Approximation; often left out",
            None,
        ),
    ],
    "amchur": [
        (
            "Zumo de limón o lima",
            "Lemon or lime juice",
            "1 cdta = 1 cda de zumo",
            "Añade líquido",
            "Adds liquid",
            None,
        ),
        ("Zumaque", "Sumac", "1 : 1", None, None, "zumaque"),
        ("Tamarindo", "Tamarind", "1 cdta = 1 cdta de pasta", None, None, "tamarindo"),
    ],
    "tamarindo": [
        (
            "Zumo de lima + azúcar moreno",
            "Lime juice + brown sugar",
            "1 cda = 1 cda zumo + 1 cdta azúcar",
            "Agridulce parecido",
            "Similar sweet-and-sour",
            None,
        ),
        ("Vinagre de arroz + azúcar", "Rice vinegar + sugar", "igual", None, None, None),
    ],
    "salsa de pescado": [
        (
            "Salsa de soja + unas gotas de zumo de lima",
            "Soy sauce + a few drops of lime juice",
            "1 : 1",
            'Menos "mar"; vale para veganos',
            'Less "sea"; works for vegans',
            None,
        ),
        (
            "Pasta de anchoas diluida",
            "Diluted anchovy paste",
            "1 cda = 1 cdta pasta + 2 cdtas agua",
            None,
            None,
            "pasta de anchoas",
        ),
    ],
    "salsa de soja": [
        ("Tamari", "Tamari", "1 : 1", "Sin gluten", "Gluten-free", "tamari"),
        (
            "Salsa Worcestershire",
            "Worcestershire sauce",
            "1 : 1",
            "Más ácida",
            "More acidic",
            "salsa worcestershire",
        ),
        (
            "Caldo + sal + una pizca de azúcar",
            "Stock + salt + a pinch of sugar",
            None,
            "Aproximación",
            "Approximation",
            None,
        ),
        ("Miso diluido", "Diluted miso", "1 cda = 1 cdta miso + agua", None, None, "miso"),
    ],
    "miso": [
        (
            "Salsa de soja + tahini",
            "Soy sauce + tahini",
            "1 cda = 1 cdta soja + 1 cdta tahini",
            None,
            None,
            None,
        ),
    ],
    "sal de apio": [
        ("Semillas de apio + sal", "Celery seed + salt", "½ + ½", None, None, None),
        ("Sal + apio fresco picado", "Salt + chopped fresh celery", None, None, None, None),
    ],
    "asafétida": [
        (
            "Ajo en polvo + cebolla en polvo",
            "Garlic powder + onion powder",
            "1 pizca = ¼ cdta de cada",
            None,
            None,
            None,
        ),
    ],
}

# blend name -> (quick_substitute_es, quick_substitute_en, note_es, [(ingredient, parts, optional)])
BLENDS = {
    "curry en polvo": (
        "Garam masala + cúrcuma (1 : 1)",
        "Garam masala + turmeric (1 : 1)",
        "Versión suave",
        [
            ("cúrcuma", "2", False),
            ("cilantro en grano", "2", False),
            ("comino", "1", False),
            ("jengibre molido", "½", False),
            ("fenogreco", "½", False),
            ("pimienta negra", "½", False),
            ("canela", "¼", False),
            ("cayena", "¼", False),
            ("cardamomo", "¼", False),
            ("clavo", "¼", False),
        ],
    ),
    "garam masala": (
        "Curry en polvo (sin cúrcuma extra) o pimienta de Jamaica + comino",
        "Curry powder (no extra turmeric) or allspice + cumin",
        None,
        [
            ("comino", "2", False),
            ("cilantro en grano", "2", False),
            ("cardamomo", "1", False),
            ("pimienta negra", "1", False),
            ("canela", "½", False),
            ("clavo", "¼", False),
            ("nuez moscada", "¼", False),
        ],
    ),
    "ras el hanout": (
        "Curry suave + canela (3 : 1)",
        "Mild curry powder + cinnamon (3 : 1)",
        None,
        [
            ("comino", "2", False),
            ("cilantro en grano", "2", False),
            ("canela", "1", False),
            ("jengibre molido", "1", False),
            ("pimentón dulce", "1", False),
            ("cúrcuma", "1", False),
            ("pimienta negra", "½", False),
            ("pimienta de jamaica", "½", False),
            ("clavo", "¼", False),
            ("nuez moscada", "¼", False),
            ("cayena", "¼", False),
        ],
    ),
    "cinco especias chinas": (
        "Anís estrellado + canela + clavo",
        "Star anise + cinnamon + cloves",
        None,
        [
            ("anís estrellado", "1", False),
            ("clavo", "1", False),
            ("casia", "1", False),
            ("pimienta de sichuan", "1", False),
            ("hinojo en grano", "1", False),
        ],
    ),
    "hierbas provenzales": (
        "Tomillo + orégano + romero",
        "Thyme + oregano + rosemary",
        None,
        [
            ("tomillo", "2", False),
            ("orégano", "2", False),
            ("romero", "1", False),
            ("mejorana", "1", False),
            ("ajedrea", "1", False),
            ("lavanda", "½", True),
        ],
    ),
    "za'atar": (
        "Tomillo + sésamo + ralladura de limón",
        "Thyme + sesame + lemon zest",
        None,
        [
            ("tomillo", "2", False),
            ("zumaque", "1", False),
            ("sésamo", "1", False),
            ("sal", "½", False),
            ("orégano", "½", True),
            ("mejorana", "½", True),
        ],
    ),
    "baharat": (
        "Ras el hanout (menos cúrcuma)",
        "Ras el hanout (less turmeric)",
        None,
        [
            ("pimienta negra", "2", False),
            ("pimentón dulce", "2", False),
            ("comino", "1", False),
            ("cilantro en grano", "1", False),
            ("canela", "1", False),
            ("clavo", "½", False),
            ("nuez moscada", "½", False),
            ("cardamomo", "½", False),
        ],
    ),
    "tandoori masala": (
        "Garam masala + pimentón + ajo",
        "Garam masala + paprika + garlic",
        None,
        [
            ("cilantro en grano", "2", False),
            ("comino", "2", False),
            ("pimentón dulce", "1", False),
            ("jengibre molido", "1", False),
            ("ajo en polvo", "1", False),
            ("cúrcuma", "½", False),
            ("cayena", "½", False),
            ("garam masala", "½", False),
        ],
    ),
    "shichimi togarashi": (
        "Copos de guindilla + sésamo + ralladura de naranja",
        "Chilli flakes + sesame + orange zest",
        None,
        [
            ("copos de guindilla", "3", False),
            ("sésamo", "1", False),
            ("cáscara de cítricos seca", "1", False),
            ("alga nori", "½", False),
            ("pimienta de sichuan", "½", False),
            ("semillas de amapola", "½", False),
            ("jengibre molido", "½", False),
        ],
    ),
    "chile en polvo": (
        "Pimentón + comino + orégano + cayena",
        "Paprika + cumin + oregano + cayenne",
        "Tex-mex",
        [
            ("chile ancho", "3", False),
            ("comino", "1", False),
            ("ajo en polvo", "1", False),
            ("orégano", "½", False),
            ("cebolla en polvo", "½", False),
            ("cayena", "¼", False),
        ],
    ),
    "cajún": (
        "Pimentón + cayena + ajo + orégano",
        "Paprika + cayenne + garlic + oregano",
        None,
        [
            ("pimentón dulce", "2", False),
            ("ajo en polvo", "1", False),
            ("cebolla en polvo", "1", False),
            ("orégano", "1", False),
            ("tomillo", "1", False),
            ("cayena", "½", False),
            ("pimienta negra", "½", False),
            ("sal", "½", False),
        ],
    ),
    "jerk": (
        "Pimienta de Jamaica + tomillo + cayena + azúcar",
        "Allspice + thyme + cayenne + sugar",
        "Jamaicano",
        [
            ("pimienta de jamaica", "2", False),
            ("tomillo", "1", False),
            ("azúcar moreno", "1", False),
            ("ajo en polvo", "1", False),
            ("cebolla en polvo", "1", False),
            ("canela", "½", False),
            ("nuez moscada", "½", False),
            ("cayena", "½", False),
            ("pimienta negra", "½", False),
        ],
    ),
    "adobo para pinchitos": (
        "Ras el hanout + pimentón (1 : 1)",
        "Ras el hanout + paprika (1 : 1)",
        "El de toda la vida en Andalucía",
        [
            ("comino", "2", False),
            ("pimentón dulce", "2", False),
            ("cilantro en grano", "1", False),
            ("cúrcuma", "1", False),
            ("ajo en polvo", "1", False),
            ("orégano", "½", False),
            ("pimienta negra", "½", False),
            ("canela", "¼", False),
            ("cayena", "¼", False),
            ("jengibre molido", "¼", False),
            ("sal", "1", False),
        ],
    ),
    "adobo para carne y pescado": (
        None,
        None,
        "Cádiz, Sevilla: con vinagre",
        [
            ("pimentón dulce", "2", False),
            ("orégano", "1", False),
            ("comino", "1", False),
            ("ajo", "1", False),
            ("laurel", "1", False),
            ("sal", "1", False),
        ],
    ),
    "mixed spice": (
        "Canela + nuez moscada + clavo",
        "Cinnamon + nutmeg + cloves",
        "Inglés, para dulces",
        [
            ("canela", "2", False),
            ("cilantro en grano", "1", False),
            ("nuez moscada", "1", False),
            ("jengibre molido", "½", False),
            ("pimienta de jamaica", "½", False),
            ("clavo", "¼", False),
        ],
    ),
    "pumpkin spice": (
        "Mixed spice o canela + jengibre",
        "Mixed spice or cinnamon + ginger",
        None,
        [
            ("canela", "3", False),
            ("jengibre molido", "2", False),
            ("nuez moscada", "1", False),
            ("pimienta de jamaica", "½", False),
            ("clavo", "½", False),
        ],
    ),
    "quatre épices": (
        "Pimienta + nuez moscada + clavo",
        "Pepper + nutmeg + cloves",
        "Francés",
        [
            ("pimienta blanca", "4", False),
            ("nuez moscada", "1", False),
            ("jengibre molido", "1", False),
            ("clavo", "½", False),
        ],
    ),
    "dukkah": (
        "Frutos secos + comino + sésamo",
        "Nuts + cumin + sesame",
        "Egipcio",
        [
            ("avellanas", "2", False),
            ("sésamo", "2", False),
            ("cilantro en grano", "1", False),
            ("comino", "1", False),
            ("sal", "½", False),
            ("pimienta negra", "½", False),
        ],
    ),
    "berberé": (
        "Cayena + pimentón + garam masala",
        "Cayenne + paprika + garam masala",
        "Etíope",
        [
            ("cayena", "3", False),
            ("pimentón dulce", "2", False),
            ("fenogreco", "1", False),
            ("jengibre molido", "1", False),
            ("cilantro en grano", "½", False),
            ("cardamomo", "½", False),
            ("clavo", "¼", False),
            ("canela", "¼", False),
            ("pimienta de jamaica", "¼", False),
            ("nuez moscada", "¼", False),
        ],
    ),
    "especias para caldereta": (
        "Pimentón + comino + laurel",
        "Paprika + cumin + bay",
        "Guiso andaluz",
        [
            ("pimentón dulce", "1", False),
            ("comino", "1", False),
            ("clavo", "1", False),
            ("pimienta negra", "1", False),
            ("laurel", "1", False),
            ("ñora", "1", False),
            ("ajo", "1", False),
        ],
    ),
}
